server:
  port: 9001

spring:
  application:
    name: goods-service
  config:
    import: configserver:http://localhost:8901
  cloud:
    config:
      profile: dev
      name: ${spring.application.name}
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
