server:
  port: 9001

spring:
  application:
    name: goods-service
  config:
    import: configserver:http://localhost:8901
  cloud:
    config:
      profile: dev
      name: ${spring.application.name}
      label: master

eureka:
  instance:
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS